skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
oddtrust_oracle = "ADh4LSG8RQpvtW4Shw8ELfM7KZJCN1Jf5cHCWanjUyF8"

[programs.localnet]
oddtrust_oracle = "ADh4LSG8RQpvtW4Shw8ELfM7KZJCN1Jf5cHCWanjUyF8"

[programs.mainnet]
oddtrust_oracle = "ADh4LSG8RQpvtW4Shw8ELfM7KZJCN1Jf5cHCWanjUyF8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "pnpm tsx tests/demo.ts"
test = "pnpm tsx --test ./tests/**/*.test.ts"
init-config = "pnpm tsx scripts/init-config.ts"

[hooks]
