import { createInterface } from "readline";
import { writeFileSync, existsSync } from "fs";
import { join } from "path";

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(query: string): Promise<string> {
  return new Promise((resolve) => rl.question(query, resolve));
}

function optional(val: string, fallback: string): string {
  return val.trim() || fallback;
}

async function main() {
  console.log("\n  OddsTrust — Environment Setup\n");

  const envPath = join(__dirname, "..", ".env.local");
  if (existsSync(envPath)) {
    const overwrite = await ask("  .env.local already exists. Overwrite? (y/N) ");
    if (overwrite.toLowerCase() !== "y") {
      console.log("  Skipping. Existing .env.local kept.\n");
      rl.close();
      return;
    }
  }

  const TXLINE_CLIENT_ID = await ask("  TxLINE Client ID: ");
  const TXLINE_WALLET_KEY = await ask("  TxLINE Wallet Key: ");
  const DATABASE_URL = await ask("  Supabase connection string (postgresql://...): ");
  const REDIS_URL = await ask("  Redis URL (redis://...): ");
  const SOLANA_RPC_URL = await ask(`  Solana RPC URL (default: https://api.devnet.solana.com): `);

  const env = [
    `# OddsTrust — Local Environment`,
    `# Generated by scripts/setup-env.ts`,
    ``,
    `NODE_ENV=development`,
    `PORT=3000`,
    `HOST=0.0.0.0`,
    `WS_PORT=3002`,
    ``,
    `# Database (Supabase PostgreSQL)`,
    `DATABASE_URL=${DATABASE_URL}`,
    ``,
    `# Redis (required for BullMQ queues + API caching)`,
    `REDIS_URL=${optional(REDIS_URL, "redis://localhost:6379")}`,
    ``,
    `# TxLINE odds data`,
    `TXLINE_API_BASE=https://api.txline.txodds.com/v1`,
    `TXLINE_WS_URL=wss://stream.txline.txodds.com/v1`,
    `TXLINE_CLIENT_ID=${TXLINE_CLIENT_ID}`,
    `TXLINE_WALLET_KEY=${TXLINE_WALLET_KEY}`,
    ``,
    `# Solana`,
    `SOLANA_RPC_URL=${optional(SOLANA_RPC_URL, "https://api.devnet.solana.com")}`,
    `SOLANA_ORACLE_PROGRAM_ID=`,
    `SOLANA_PAYER_KEY=`,
    ``,
    `# Logging`,
    `LOG_LEVEL=info`,
    `LOG_PRETTY=true`,
    ``,
    `# Redis channels`,
    `REDIS_PROOF_FEED_CHANNEL=proof-feed:live`,
    ``,
    `# Rate limiting`,
    `API_RATE_LIMIT_MAX=100`,
    `API_RATE_LIMIT_WINDOW_MS=60000`,
    ``,
  ].join("\n");

  writeFileSync(envPath, env, "utf-8");
  console.log(`\n  Written to .env.local\n`);

  console.log("  Next steps:");
  console.log(`    pnpm db:migrate    # run Supabase schema migrations`);
  console.log(`    pnpm dev           # start the dev server`);
  console.log(`    pnpm start:worker  # start the odds worker`);
  console.log(`    pnpm start:ws      # start the WebSocket server\n`);

  rl.close();
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
